### ISSUE TITLE
Support for html5 `<picture>` and `srcset` attributes 

### ISSUE THREAD

**Issue by shauunhimseelf** [nails/module-cdn#164]
The HTML5 `picture` element allows browser level selection and rendering of responsive images. 
- [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture)

## API Design
- An example tag
```html
<picture>
  <source srcset="logo-768.png 768w, logo-768-1.5x.png 1.5x"> // The `w` property sets the minimum width
  <source srcset="logo-480.png, logo-480-2x.png 2x">          // The last property checks the pixel density 
  <source srcset="logo.webp" type="image/webp">               // The type can check browser support for format
  <img src="logo-320.png" alt="logo">                         // Fallback
</picture>
```

- The existing Picture API is fairly futureproof in that the `img` specified inside the tag will be used where a non-html5 compliant browser is used. However, as it might break styling where we're using `flex` or where front end devs have been lazy and styled `img` directly, we might be best using this as either something that's turned on via an option, or via a new function.
- It would be good to still be able to use existing CDN methods (`crop/scale`) with this, but I wonder in practice how that would work (chaining?).

## Suggested API
```
???
```

**Comment by hellopablo** [comment]
I suspect we'll need to introduce a `Nails\Cdn\Helper\Picture` class which can generate the markup based on some defined parameters. Will need to determine how the arguments are structured though. Maybe something like:

```php
$picture = new Picture($cdnObjectOrId);
$picture
    ->source($width, $height, $breakpoint, $density)
    ->source($width, $height, $breakpoint, $density)
    ->fallback($width, $height);

echo $picture;
```
Could probably find a way to wrap that up into a more template friendly helper function. Above will likely need some more thought.
